import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Link from "next/link";
import { getSession } from "@/auth/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/2e5130a48b.js" crossOrigin="anonymous"></Script>
      <body className={inter.className}>
        <nav className="bg-black px-6 py-5 fixed w-full flex top-0 left-0 text-gray-400 text-sm font-medium tracking-wide border-b-xs justify-between border-gray-900">
          <div className="flex gap-4">
            <Link className="hover:text-gray-200 transition-colors duration-300" href="/">Home</Link>
            <Link className="hover:text-gray-200 transition-colors duration-300" href="/">Projects</Link>
          </div>
          {session && <button className="hover:text-gray-200 transition-colors duration-300">Log out</button>}
        </nav>
        {children}
      </body>
    </html>
  );
}
